apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduk8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eduk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: eduk8s-operator
    spec:
      serviceAccountName: eduk8s
      containers:
      - name: eduk8s
        image: projects.registry.vmware.com/educates/educates-operator-test:210608.182918.84fbf29
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: eduk8s-images
            optional: true
